# Generated by Django 4.2.1 on 2023-06-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.CharField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyUAB_Hbdz5YjruXOXnXEOH5HlUE1mSupuT8hVfRd0gA&s', max_length=255, null=True),
        ),
    ]
