# Generated by Django 4.2.1 on 2023-06-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='image',
            field=models.CharField(blank=True, default='https://im1.dineout.co.in/images/uploads/misc/2019/Jul/1/7.png', max_length=200),
        ),
    ]
