# Generated by Django 4.2.1 on 2023-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
