# Generated by Django 4.2.1 on 2023-05-26 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_payment_id',
            field=models.CharField(default='pay_default', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='unit_charge',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='restaurant.table'),
        ),
    ]
