# Generated by Django 4.2.1 on 2023-05-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='email',
        ),
    ]
