# Generated by Django 4.2.1 on 2023-05-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_restaurant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=models.URLField(default='https://lh3.googleusercontent.com/rJ1grb0qDv7Q0nVuU1hIu4BclOz_MsNent80GS2SSCc8gFtJiKfn9mhLoM3CFS1Z3TwDXIwZHecQNPwxuByzxYs0RkPx10olzBruars=w1000-rw'),
        ),
        migrations.AlterField(
            model_name='resimage',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80', max_length=250),
        ),
    ]
