# Generated by Django 4.2.1 on 2023-06-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_menuimage_image_alter_resimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
